### ISSUE TITLE
How to save data?

### ISSUE THREAD

**Issue by billieblaze** [motherinc/mongoose-timeseries#1]
Looking over the readme and the code, its not really clear how to submit a sample.   I'll keep looking, but if you had any pointers that'd be super!

**Comment by billieblaze** [comment]
actually, I figured that part out, but now the findOneAndUpdate isn't creating a new document.

**Comment by jaredreich** [comment]
Hey billieblaze, thanks for the bringing this up.

This is by design - this plugin uses the `save` hook rather than `findOneAndUpdate` hook.

See here for more info: https://github.com/Automattic/mongoose/issues/3970

This specifically occurs here (in index.js):

``` js
schema.post('save', function () { ...
```
